language: node_js
node_js:
- node
env:
  global:
    secure: XhFFxhHdcJqvByZBk5SiFP7c4BiIy/1Y/MZXda2L1RBMNiR9nK4xfapvXOV/QHOBVThXriq0f+vt8P/4tLiiHhRunhV81iNoS5GsCQRoaxO5QG5A2WzIKFNSPjgKMGsz3mDXbxBD0EHY4jQl2uOxd9qdgOUBc6isJHeTw37qRhx9hzb+jDiHpuoFzfS5AIjqnoSfDKhhF6BGZMizcefyjTLiMReAiCwoWTKVw2Y4jEHTGoCG1pxbL2wDmTe5krQDhSseiy/711c79RzcvEk5rcSvuzV7eLgispI5PCyKI3bnNjOFU6BnYP6aHfw7OXrVmTXmqZF8RhHLEnQk6hBHrKpdctCo+nvA6maBTF03VDYk7Y5Wn0IfF5/u7h//TLOSdC13VXDcQfZ+VkMistFNBOQGbMoTWlzfk+PBK/b22lkq17Wp7rC0zWn9lVbZP5l/gA/9MZeh+B9DhdqX12x1IfC1QxK4Sk7oZN7aEdva3d2EAVje3B33DCpRr0Zbvk71rKFit3GfyFSGkpMT6OlXGEsQQNTQwkwvvOTe4YvE3+rICOIEZP6Liwl3HlXtQzFGOxKIWy/e/V1fkrZKCIQJs3E9IVdgeoYtQl88sBH9Z+SHawIXdkwWBvimGYTqlcs5hEhYTaGrIGwbMpsUJdX3ZeIAnlyIlUS5TYeDYq5j/xw=

